version: '0.0.1'
services:
    web:
      build: .
      command: npm run dev
      restart: always
      ports:
         -  "7001:7001" 
    
    front:
      image: docker.io/nginx:latest
      restart: always
      ports:
          -  "8080:80"
      volumes:
         - ./F/dist:/usr/share/nginx/html:ro         
